### ISSUE TITLE
7.6.3 (<7.6.7) 版本的 web 登录

### ISSUE THREAD

**Issue by Hagb** [lyc8503/EasierConnect#1]
非常感谢作者的工作！（之前我一直想逆向但是能力有限没有成功）
似乎 EasyConnect <7.6.7 版本的登录过程中所使用的 api 有些区别：

1. `/por/login_auth.csp?apiversion=1` 可能没有 `CSRF_RAND_CODE`，此时加密密码直接使用 `password` 而非 `password+"_"+csrfCode`
2. `/por/login_psw.csp` 需要加 `type=cs` 这个参数才会返回 xml
3. `/por/login_psw.csp` 返回的 body 中没有 `<NextService>`，而只有 `<NextAuth>`:
    1. “没有下一步验证” 由  `<NextAuth>-1</NextAuth>` 表示（此时若还有 `<Result>1</Result>` 那么应该是登录成功）
    2. “有下一步认证” 由 `<NextAuth>编号</NextAuth>` 和 `<Result>2</Result>` 表示（在我的测试中硬件特征码的编号为 `4`）
    3. 认证失败由 `<Result>0</Result>` 表示

做了以下修改后可以登录 <7.6.7 且仅有帐号、密码认证的 EasyConnect，并且可以访问 vpn 一侧的内网站点
```diff
diff --git a/web_login.go b/web_login.go
index b4a8955..a3849a5 100644
--- a/web_login.go
+++ b/web_login.go
@@ -49,7 +49,12 @@ func WebLogin(server string, username string, password string) string {
 	rsaExp := string(regexp.MustCompile(`<RSA_ENCRYPT_EXP>(.*)</RSA_ENCRYPT_EXP>`).FindSubmatch(buf[:n])[1])
 	log.Printf("RSA Exp: %s", rsaExp)
 
-	csrfCode := string(regexp.MustCompile(`<CSRF_RAND_CODE>(.*)</CSRF_RAND_CODE>`).FindSubmatch(buf[:n])[1])
+	csrfMatch := regexp.MustCompile(`<CSRF_RAND_CODE>(.*)</CSRF_RAND_CODE>`).FindSubmatch(buf[:n])
+	csrfCode := ""
+	if csrfMatch != nil {
+		csrfCode := string(csrfMatch[1])
+		password += "_" + csrfCode
+	}
 	log.Printf("CSRF Code: %s", csrfCode)
 
 	pubKey := rsa.PublicKey{}
@@ -58,14 +63,14 @@ func WebLogin(server string, username string, password string) string {
 	moduls.SetString(rsaKey, 16)
 	pubKey.N = &moduls
 
-	encryptedPassword, err := rsa.EncryptPKCS1v15(rand.Reader, &pubKey, []byte(password+"_"+csrfCode))
+	encryptedPassword, err := rsa.EncryptPKCS1v15(rand.Reader, &pubKey, []byte(password))
 	if err != nil {
 		panic(err)
 	}
 	encryptedPasswordHex := hex.EncodeToString(encryptedPassword)
 	log.Printf("Encrypted Password: %s", encryptedPasswordHex)
 
-	addr = server + "/por/login_psw.csp?anti_replay=1&encrypt=1"
+	addr = server + "/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs"
 	log.Printf("Login Request: %s", addr)
 
 	form := url.Values{
@@ -87,7 +92,7 @@ func WebLogin(server string, username string, password string) string {
 	n, _ = resp.Body.Read(buf)
 	defer resp.Body.Close()
 
-	if !strings.Contains(string(buf[:n]), "Auth is success") {
+	if strings.Contains(string(buf[:n]), "<Result>0</Result>") {
 		panic("Login FAILED: " + string(buf[:n]))
 	}
 
@@ -142,7 +147,10 @@ func WebLogin(server string, username string, password string) string {
 		log.Print("SMS Code verification SUCCESS")
 
 	} else {
-		panic("not implemented: sms not required")
+		nextAuth := string(regexp.MustCompile(`<NextAuth>(.*)</NextAuth>`).FindSubmatch(buf[:n])[1])
+		if nextAuth != "-1" {
+			panic("not implemented nextAuth: "+nextAuth)
+		}
 	}
 
 	log.Printf("Web Login process done.")

```

update: 代码里的 tab 我不小心弄成空格了，现在改回来了

**Comment by lyc8503** [comment]
非常感谢你贡献的代码 😃
正好我也没有别的版本的 EasyConnect 账号和服务器可以测试, 不了解其他版本的协议是怎么实现的.
那现在看来 7.6.3 版本的二进制部分的协议和 7.6.7 是兼容的, 只是在网页登录的 api 上有少许不同.

现在这个程序主体功能基本完成了, 但还不是很稳定, 我再测试一下, 底层协议稳定之后会尝试修改一下 Web 登录的部分来兼容 7.6.3 版本.

**Comment by Hagb** [comment]
>  正好我也没有别的版本的 EasyConnect 账号和服务器可以测试, 不了解其他版本的协议是怎么实现的.

关于这个我给你发了封邮件，应该可以收到？

> 现在这个程序主体功能基本完成了, 但还不是很稳定, 我再测试一下, 底层协议稳定之后会尝试修改一下 Web 登录的部分来兼容 7.6.3 版本.

18e7f1fad7b0f47e1814af621ee3d58062a20fbd 之后我测试也没有遇到 EOF 退出或者其它类型的错误了（不过测试时间还不长）。

**Comment by lyc8503** [comment]
@Hagb 已在 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild7 中提供支持.

**Comment by Hagb** [comment]
> @Hagb 已在 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild7 中提供支持.

感谢作者。有个小问题，传给 7.6.3 服务端的 csrfCode 参数似乎不能为 `"WARNING: No Match. Maybe you're connecting to an older server? Continue anyway..."`（空字符串可以，奇怪的是并非所有非空字符串都会引起问题），否则会报 `You are trying brute-force login. The user account is locked` ，具体地说 `/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs` 返回 `<?xml version="1.0" encoding="utf-8"?><Auth><Result>0</Result> <EnableMAM>1</EnableMAM><SuportMDM>0</SuportMDM><CurAuth>1</CurAuth><NextAuth>-1</NextAuth><AuthInfo><![CDATA[]]></AuthInfo><Note><![CDATA[You are trying brute-force login. The user account is locked!]]></Note><ChallengeMsg><![CDATA[]]></ChallengeMsg><SmsIsStillValid>0</SmsIsStillValid><Phone><![CDATA[]]></Phone><CurPhone><![CDATA[]]></CurPhone><SmsSendType><![CDATA[default]]></SmsSendType><mdmEnable>0</mdmEnable><mdmUqid></mdmUqid><MdmUrl>https://:0</MdmUrl><RootRule>-1</RootRule></Auth>
`）.

新年快乐！

**Comment by lyc8503** [comment]
> > @Hagb 已在 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild7 中提供支持.
> 
> 感谢作者。有个小问题，传给 7.6.3 服务端的 csrfCode 参数似乎不能为 `"WARNING: No Match. Maybe you're connecting to an older server? Continue anyway..."`（空字符串可以，奇怪的是并非所有非空字符串都会引起问题），否则会报 `You are trying brute-force login. The user account is locked` ，具体地说 `/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs` 返回 `<?xml version="1.0" encoding="utf-8"?><Auth><Result>0</Result> <EnableMAM>1</EnableMAM><SuportMDM>0</SuportMDM><CurAuth>1</CurAuth><NextAuth>-1</NextAuth><AuthInfo><![CDATA[]]></AuthInfo><Note><![CDATA[You are trying brute-force login. The user account is locked!]]></Note><ChallengeMsg><![CDATA[]]></ChallengeMsg><SmsIsStillValid>0</SmsIsStillValid><Phone><![CDATA[]]></Phone><CurPhone><![CDATA[]]></CurPhone><SmsSendType><![CDATA[default]]></SmsSendType><mdmEnable>0</mdmEnable><mdmUqid></mdmUqid><MdmUrl>https://:0</MdmUrl><RootRule>-1</RootRule></Auth> `）.
> 
> 新年快乐！

新年快乐! 不好意思忘了后面还要把参数传给服务器了hh 本来只是想改一下显示输出的 没测试周全 我明天修改一下代码.

**Comment by lyc8503** [comment]
怀疑传这个字符串不行的原因是其中有单引号/问号这些特殊字符, 参数检查的时候直接被拦截下来了. 我明天把它修改成传递空串.

**Comment by Hagb** [comment]
> 怀疑传这个字符串不行的原因是其中有单引号/问号这些特殊字符, 参数检查的时候直接被拦截下来了. 我明天把它修改成传递空串.

确实，我把 `you're` 改成 `you are` 就可以了

**Comment by lyc8503** [comment]
在 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild8 中修复

**Comment by lyc8503** [comment]
在最新版本中优化了相关实现.
