### ISSUE TITLE
报错Error occurred while send

### ISSUE THREAD

**Issue by peaceanddemocracy** [lyc8503/EasierConnect#10]
2023/01/23 21:27:48 Error occurred while send, retrying: unexpected send handshake reply panic: send retry limit exceeded.

**Comment by peaceanddemocracy** [comment]
连上后几秒钟断开

**Comment by lyc8503** [comment]
请问你具体使用的 EasyConnect 的版本是?

**Comment by peaceanddemocracy** [comment]
> 请问你具体使用的 EasyConnect 的版本是?



> 请问你具体使用的 EasyConnect 的版本是?

不太清楚，应该是自动更新的最新版的，release的可以运行连接几秒钟，然后就断开了

**Comment by peaceanddemocracy** [comment]
> 请问你具体使用的 EasyConnect 的版本是?

安装包显示的是7.6.6.1这个版本的

**Comment by peaceanddemocracy** [comment]
使用的是win64的release文件

**Comment by lyc8503** [comment]
是否可以尝试一下添加 --debug-dump 参数运行并给出结尾处的日志. (注意处理敏感信息)

**Comment by peaceanddemocracy** [comment]
> 是否可以尝试一下添加 --debug-dump 参数运行并给出结尾处的日志. (注意处理敏感信息)

![image](https://user-images.githubusercontent.com/10943213/214098391-94f49174-947c-44cd-8e33-07bd6b89a0e7.png)

**Comment by lyc8503** [comment]
需要截一下上面的 16 进制 hexdump

**Comment by peaceanddemocracy** [comment]
> 需要截一下上面的 16 进制 hexdump

![image](https://user-images.githubusercontent.com/10943213/214201244-6753f916-331d-460b-a584-daa785728e78.png)
是这个么？

**Comment by peaceanddemocracy** [comment]
猜测会不会和easyconnect服务端限制了并发连接数有关

**Comment by xavierskip** [comment]
试了一下，可以正常登陆，打开网页，但是打开第二个网页就程序就退出了，我然后试着保持页面打开不打开新页面，可以看到网页里的 xhr 请求是正常的，但是一打开新页面程序就退出了。很可能是上面说的并发连接数的关系。

终端里显示的log是这样的
```
2023/01/24 14:19:27 socks dial: 10.68.0.1:80
2023/01/24 14:19:27 socks dial: 10.68.0.1:80
2023/01/24 14:19:27 socks dial: 10.68.0.1:80
2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 recv handshake: wrote 64 bytes
00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 recv handshake: wrote 64 bytes
00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 recv handshake: wrote 64 bytes
00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
2023/01/24 14:19:27 recv handshake: wrote 64 bytes
00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
panic: recv retry limit exceeded.

goroutine 38 [running]:
EasierConnect/core.StartProtocol.func1()
        EasierConnect/core/protocol.go:196 +0x105
created by EasierConnect/core.StartProtocol
        EasierConnect/core/protocol.go:199 +0xd2
```

**Comment by peaceanddemocracy** [comment]
> 试了一下，可以正常登陆，打开网页，但是打开第二个网页就程序就退出了，我然后试着保持页面打开不打开新页面，可以看到网页里的 xhr 请求是正常的，但是一打开新页面程序就退出了。很可能是上面说的并发连接数的关系。
> 
> 终端里显示的log是这样的
> 
> ```
> 2023/01/24 14:19:27 socks dial: 10.68.0.1:80
> 2023/01/24 14:19:27 socks dial: 10.68.0.1:80
> 2023/01/24 14:19:27 socks dial: 10.68.0.1:80
> 2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
> 2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 recv handshake: wrote 64 bytes
> 00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
> 00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
> 00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
> 00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
> 2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
> 2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 recv handshake: wrote 64 bytes
> 00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
> 00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
> 00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
> 00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
> 2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
> 2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 recv handshake: wrote 64 bytes
> 00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
> 00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
> 00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
> 00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
> 2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
> 2023/01/24 14:19:27 socket: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 tls: connected to:  x.x.x.x:8443
> 2023/01/24 14:19:27 recv handshake: wrote 64 bytes
> 00000000  06 00 00 00 36 37 61 64  37 62 31 63 32 32 31 63  |....67ad7b1c221c|
> 00000010  66 62 34 37 31 64 63 36  61 36 37 39 63 31 36 63  |fb471dc6a679c16c|
> 00000020  66 37 31 00 30 38 36 30  31 30 35 61 32 39 36 35  |f71.0860105a2965|
> 00000030  33 62 66 38 00 00 00 00  00 00 00 00 03 01 00 02  |3bf8............|
> 2023/01/24 14:19:27 Error occurred while recv, retrying: EOF
> panic: recv retry limit exceeded.
> 
> goroutine 38 [running]:
> EasierConnect/core.StartProtocol.func1()
>         EasierConnect/core/protocol.go:196 +0x105
> created by EasierConnect/core.StartProtocol
>         EasierConnect/core/protocol.go:199 +0xd2
> ```

我和你这个情况一样，猜测是并发数，easyconnect客户端一般是根据服务端要求限制并发数的，超过了就自动掉线

**Comment by lyc8503** [comment]
怀疑1: 服务器有并发数限制
怀疑2: 服务器版本所用的二进制协议有其他差异

我这里不太方便测试, 欢迎修改后 PR.

**Comment by peaceanddemocracy** [comment]
> 怀疑1: 服务器有并发数限制 怀疑2: 服务器版本所用的二进制协议有其他差异
> 
> 我这里不太方便测试, 欢迎修改后 PR.

不太懂这个，大佬能否加上一个并发连接数的限制参数上去，我测试下

**Comment by i-Pear** [comment]
用脚本做了下测试 单线程下也有这个问题 更像是数据传输到一定量就会触发
如果控制住下载量 即使是多线程也不会报错

**Comment by peaceanddemocracy** [comment]
> 

是不是和easyconnect服务端的限速有关，每个客户端限速，超速后就自动断开

**Comment by i-Pear** [comment]
> > 
> 
> 是不是和easyconnect服务端的限速有关，每个客户端限速，超速后就自动断开

应该和限速没关系
因为EasierConnect本身有一个buffer 所以在下载工具里限速是没有意义的
我在 https://github.com/lyc8503/EasierConnect/blob/main/core/protocol.go#L121 之后加了个sleep，把接收速度限制到10kb左右，还是出现一样的错误

**Comment by lyc8503** [comment]
> 用脚本做了下测试 单线程下也有这个问题 更像是数据传输到一定量就会触发 如果控制住下载量 即使是多线程也不会报错

@i-Pear 我看你简介写的是 NJU, 你现在连接的是 vpn.nju.edu.cn 吗, 我没法复现这个问题.

服务端是会在客户端做出一些违反规定的行为时直接结束流导致 EOF, 但不知道这里触发服务器断开的因素是什么.

**Comment by i-Pear** [comment]
> > 用脚本做了下测试 单线程下也有这个问题 更像是数据传输到一定量就会触发 如果控制住下载量 即使是多线程也不会报错
> 
> @i-Pear 我看你简介写的是 NJU, 你现在连接的是 vpn.nju.edu.cn 吗, 我没法复现这个问题.
> 
> 服务端是会在客户端做出一些违反规定的行为时直接结束流导致 EOF, 但不知道这里触发服务器断开的因素是什么.

是的 我使用vpn.nju.edu.cn
我在内网的服务器上放了几个文件，这是我的测试脚本：https://pastebin.com/Usyipfnt
报错如下：https://pastebin.com/JcNr1k49
环境是macos 13.1 M1

在aliyun上用ubuntu测了下 报错相同 应该不是环境问题

**Comment by lyc8503** [comment]
嗯, 感谢你的信息, 我成功复现了, 我以为这个 Bug 我已经在 https://github.com/lyc8503/EasierConnect/commit/18e7f1fad7b0f47e1814af621ee3d58062a20fbd 中修复了.

这个 Bug 应该是因为 QueryIp 这个连接被关闭了, 服务器就会断开之后的连接, 

但之前的修复在后面的代码整理过程中不知道为什么又出现了(怪我对 golang 学艺不精qvq), 但因为没法回归测试没及时发现, 以为这个 Bug 是新的 Bug.

我应该找到原因了, 明天尝试修复一下.

**Comment by lyc8503** [comment]
https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild8 应该没有这个问题

**Comment by i-Pear** [comment]
> https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild8 应该没有这个问题

是的 这个版本没有问题

**Comment by i-Pear** [comment]
跟了一下发现queryConn的connected会变成false；然后用runtime.SetFinalizer打log，确认是client被gc了
加一个runtime.KeepAlive就好了
因为EasyConnectClient里面只有endpoint和ipStack在使用，而这两个是指针，所以确实可以gc

**Comment by lyc8503** [comment]
感谢你的解释和 PR, 我明白这东西是怎么被 gc 的了.hh
我开始以为我把 client 指针存在 main 的 stack 里, client 就是可达的, client 自己就一定不会被回收, 所以从 client -> queryConn 是可达的.

没想到 golang 还会这样做 gc, 我再去研究一下相关资料.

**Comment by 724399396** [comment]
发现部分版本里面，哪怕queryConn不被GC,在10次TCP的Keep-Alive之后，服务端会向queryConn发送一个数据包，数据包内容为00000000  0f 00 00 00 00 00 00 00  00 16 78 dd 8a bd 50 cc  |..........x...P.|
00000010  b0 77 1d 11 fc 7f 00 00  17 1c 75 11 bd 7f 00 00  |.w........u.....|
00000020  50 a2 c5 12                                       |P...|
，如果不对这个包进行响应就会导致recv conn的Read获取到EOF，目前还没发现需要怎么回复这个包
