### ISSUE TITLE
Login failed with vpn.tju.edu.cn at win11

### ISSUE THREAD

**Issue by supernova4869** [lyc8503/EasierConnect#13]
I tried to use vpn on win11 but got this error:
```
2023/01/24 20:42:48 Login Request: https://vpn.tju.edu.cn:443/por/login_psw.csp?anti_replay=1&encrypt=1&type=cs
2023/01/24 20:42:48 No NextAuth found.
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x83
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x1a
EasierConnect/core.WebLogin({0x11c9a540, 0x12}, {0x11c96140, 0xa}, {0x11c96178, 0x8})
        EasierConnect/core/web_login.go:142 +0x1963
EasierConnect/core.(*EasyConnectClient).Login(0x11ca9f80, {0x11c96140, 0xa}, {0x11c96178, 0x8})
        EasierConnect/core/EasyConnectClient.go:35 +0x8d
main.main()
        EasierConnect/main.go:38 +0x623
2023/01/24 20:42:48 Login FAILED: <?xml version="1.0" encoding="utf-8"?>
<Auth>
        <LBEnabled>0</LBEnabled>
        <CSRF_RAND_CODE>121068608</CSRF_RAND_CODE>
        <AuthInfo><![CDATA[]]></AuthInfo>
        <Note><![CDATA[Server forbidden access!]]></Note>
        <ErrorCode>20113</ErrorCode>
        <Result>0</Result>
        <Message><![CDATA[not allow to login now]]></Message>
</Auth>
```

**Comment by lyc8503** [comment]
I have no idea why the server is returning `Server forbidden access!` and `not allow to login now`.

Can you login successfully with same credentials in the official EasyConnect client, or could you try logging in again with EasierConnect later?

**Comment by lyc8503** [comment]
Do you need TOTP to login to your server? Maybe your issue is duplicate with #11 .

**Comment by supernova4869** [comment]
> I have no idea why the server is returning `Server forbidden access!` and `not allow to login now`.
> 
> Can you login successfully with same credentials in the official EasyConnect client, or could you try logging in again with EasierConnect later?

Yes, the official EasyConnect works correctly, but it steals the 80 port, so I tried this EasierConnect. And I tried again just now, and got the same error. Seems it is due to something of the vpn server.

**Comment by lyc8503** [comment]
As you have commented in #11, closing this issue as duplicated.
