### ISSUE TITLE
运行时报错,怀疑服务端版本太低

### ISSUE THREAD

**Issue by not7sa** [lyc8503/EasierConnect#21]
最新版本12运行时报错如下:
panic: runtime error: index out of range [1] with length 0

goroutine 1 [running]:
EasierConnect/core.WebLogin({0xc000020600?, 0x2?}, {0xc000022130, 0x7}, {0xc000022168, 0x8})
        EasierConnect/core/web_login.go:53 +0x192a
EasierConnect/core.(*EasyConnectClient).Login(0xc000095ef0, {0xc000022130?, 0xc000095e90?}, {0xc000022168?, 0x2?})
        EasierConnect/core/EasyConnectClient.go:35 +0x91
main.main()
        EasierConnect/main.go:39 +0x5bb
怀疑服务端版本太低,本软件是否不支持服务器端版本低于7.5的,如果是的话,有计划支持么?

**Comment by lyc8503** [comment]
Please try https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild13.
