### ISSUE TITLE
能否提供socks5的鉴权功能？

### ISSUE THREAD

**Issue by xiadd** [lyc8503/EasierConnect#23]
如题。

我是部署在家里的路由器上，暴露在公网上，希望能加上鉴权功能提高安全性。

**Comment by cmj2002** [comment]
强烈建议您不要这么做，因为**即使是带密码的 SOCKS5 代理的通讯依旧是明文传输的**，不仅您访问的 IP 和端口会暴露，如果贵组织在内网使用了 HTTP 等未加密的网络协议，你的通讯明文也会暴露在公网上（包括你输入的密码、可用于鉴权的 cookies 、内部网站上的敏感信息等）。

如果您真的需要公网访问，您可以使用 [gost](https://github.com/ginuerzh/gost) 将 SOCKS5 代理转发为加密通讯的 Shadowsocks 或 HTTPS 代理（同样不建议 HTTP 代理）使用。

基于同样的理由，我也不建议作者实现鉴权功能，以免造成一种“我加了密码所以很安全”的错觉，降低网络安全性。

**Comment by xiadd** [comment]
> 强烈建议您不要这么做，因为**即使是带密码的 SOCKS5 代理的通讯依旧是明文传输的**，不仅您访问的 IP 和端口会暴露，如果贵组织在内网使用了 HTTP 等未加密的网络协议，你的通讯明文也会暴露在公网上（包括你输入的密码、可用于鉴权的 cookies 、内部网站上的敏感信息等）。
> 
> 如果您真的需要公网访问，您可以使用 [gost](https://github.com/ginuerzh/gost) 将 SOCKS5 代理转发为加密通讯的 Shadowsocks 或 HTTPS 代理（同样不建议 HTTP 代理）使用。
> 
> 基于同样的理由，我也不建议作者实现鉴权功能，以免造成一种“我加了密码所以很安全”的错觉，降低网络安全性。

感谢回复，我看了一下gost确实很好用，我之前是想用tinyproxy转发代理的，刚刚知道这个软件，再次感谢

**Comment by lyc8503** [comment]
我也不打算加入鉴权功能, 因为上游依赖也没有这个功能. socks5 暴露在公网上确实也不太安全, gost / SSH Tunnel / v2ray 之类的都可以安全地转发 socks 代理.

本软件的初衷部分也是希望可以直接在终端设备上方便的连接到 EasyConnect 服务器, 你也可以尝试不用转发, 直接在需要连接的终端上运行 EasierConnect.
