### ISSUE TITLE
可以登录但是服务器不回应连接

### ISSUE THREAD

**Issue by githuu5y5u** [lyc8503/EasierConnect#25]
https://gist.github.com/githuu5y5u/e9d20ef43f46f61bf0171ed1cea18538
登录一切正常 (-twf-id 方式) 且试了远端路由表上的IP但就是走不通, 原版客户端版本 7.6.11 一切正常

**Comment by githuu5y5u** [comment]
Same as https://github.com/lyc8503/EasierConnect/issues/17

**Comment by githuu5y5u** [comment]
![屏幕截图 2023-01-26 183109](https://user-images.githubusercontent.com/101561670/214814538-77c3c1d1-33e8-4220-ad38-fa74a35b4fde.png)
今天刚下的客户端 抓出来的TLS 1 包带这个警告， 但是 EasierConnect 抓出来的没有 不知道和这个有没有关系
@lyc8503

**Comment by githuu5y5u** [comment]
比对了一下 客户端的文件 可以确认不是版本更新导致的问题

**Comment by lyc8503** [comment]
这是 TLS 握手阶段的 Unknown Record, 可能又是什么 EasyConnect 协议中夹带的私货, 之前没发现类似的内容, 不太清楚.
