### ISSUE TITLE
是否有创建GUI项目的计划从而更易于使用？

### ISSUE THREAD

**Issue by LincolnYe** [lyc8503/EasierConnect#3]
如果该程序可以有容易的启动方式，那么设计一个简单的登录UI，并后台于状态栏方便重新连接，那么将更方便使用？
我的一些想法有：
1、分出核心package , cli和gui程序可以分别完成
2、考虑一些Go的跨平台易于使用的GUI库实现，如fyne等
3、使用Electron等套壳cli程序。

最后，感谢作者的贡献！

**Comment by lyc8503** [comment]
感谢你的提议, 这是我写的第一个 golang 项目, 可能结构上还有改进的空间. 我接下来会尝试分 package 使结构更加合理.
至于 GUI, 个人感觉 GUI 的需求不是十分迫切, 程序使用命令行参数输入信息也是最直白简明的方式, 程序需要展示的信息也不多(目前是连接信息), 在 log 中也足以展现了.
Electron 这种方案过于臃肿了, Electron 打包后的体积和内存占用很可能远远超过程序本体, 个人觉得没有必要.

在**比较简洁且占用资源较少**的情况下, 我觉得可以加入简单的**原生**登录UI+托盘图标+托盘图标右键菜单/悬浮显示的方式使大家在图形界面下更方便地使用该客户端.

不过考虑到可能有相当数量的人还是只使用 cli 运行该程序, 我也倾向于将 cli 和 gui 版本的客户端分开发布.

我自己对 golang 也还不是特别熟悉, 也不怎么开发桌面应用, 所以相关的功能欢迎 PR.

最后, 祝新年快乐!

**Comment by lyc8503** [comment]
Solved in PR #7
