### ISSUE TITLE
[Feature Request] 使用企业微信登陆

### ISSUE THREAD

**Issue by SherkeyXD** [lyc8503/EasierConnect#34]
同#26，算是提供图片示例吧

<img width="655" alt="image" src="https://user-images.githubusercontent.com/57581480/215381560-2c3c5edb-4280-44e6-80ba-78bca13ea940.png">

可否像qq机器人登陆那样，在终端显示二维码并要求扫描？

~~如果难实现就当我没说过~~

**Comment by lyc8503** [comment]
企业微信登录应该不是标准的登录流程, 应该是深信服为 XMU 定制的, 可以如 #26 中提到的用 TwfID 登录, 稍后应该会支持直接在网页上登录, 大概率不会支持在终端登录(除非有人提起相关 PR).

如果有其他问题还可以继续在 #26 下面留言~ 为了方便管理我先把这个 issue close 了.
