### ISSUE TITLE
windows-amd64 闪一下就没了

### ISSUE THREAD

**Issue by singdoo** [lyc8503/EasierConnect#35]
求助大佬，系统 Windows11 22H2
cpu AMD Ryzen 7 5800H
下载 TestBuild14 里面的 EasierConnect-windows-amd64.zip ，解压双击闪一下就没了，可咋整？

**Comment by lyc8503** [comment]
命令行程序, 请使用 cmd/powershell 运行. GUI 版本的目前因为交叉编译不便还没加入 Releases.

**Comment by singdoo** [comment]
> 命令行程序, 请使用 cmd/powershell 运行. GUI 版本的目前因为交叉编译不便还没加入 Releases.

好的  收到
