### ISSUE TITLE
使用release中预打包的二进制可以稳定运行，自行打包的二进制在某些时刻会报错。

### ISSUE THREAD

**Issue by GitHubUserC** [lyc8503/EasierConnect#39]
系统环境：
```
Microsoft Windows 11 专业版
10.0.22621 暂缺 Build 22621
go 1.19.10
```

打包命令：
`go build main.go`
`go build -v -o EasierConnect.exe -trimpath -ldflags "-s -w -buildid=" .`
都试过，结果一样。

执行命令：
`.\EasierConnect.exe -server xxxx -port xxxx -username xxxx -password xxxx`

报错详情：
```
goroutine 34 [running]:
EasierConnect/core.StartProtocol.func2()
        D:/go/src/github.com/EasierConnect/core/protocol.go:210 +0x105
created by EasierConnect/core.StartProtocol
        D:/go/src/github.com/EasierConnect/core/protocol.go:213 +0x167
```

报错场景：
自行打包版本运行未直接报错，访问大部分网站也都OK，但就是存在一两个网站访问时会报上述错误。
使用release中预打包的二进制同样的命令运行，访问前述出问题的网站一切如常。

**Comment by lyc8503** [comment]
目前有 dev 和 main 两个分支, 有两个不同版本的 release, 请先确认版本是否一致.

**Comment by GitHubUserC** [comment]
经测试，dev分支确实不会出问题，谢谢。
