### ISSUE TITLE
添加通过 twfId 来登录的选项

### ISSUE THREAD

**Issue by Hagb** [lyc8503/EasierConnect#4]
有可能通过截获 EasyConnect 官方客户端的服务进程和前端（服务端网页/客户端gui）的通讯来获取登录后的 twfId，从而将其用于给 EasierConnect 连接 vpn。

除了调试外，主要的应用场景可能是遇到 EasierConnect 尚未适配的登录方式时，作为一种暂时的变通方式，也可以尽可能地由开源实现来连接深信服的 vpn。即：仅登录部分需要使用深信服专有客户端的一部分，其余部分由 EasierConnect 完成。在 GNU/Linux 版的 EasyConnect 官方客户端中，对这个深信服的服务进程或许可以做到（相比于 docker/podman）较为轻量级的隔离（待验证）。

**Comment by lyc8503** [comment]
开发时有过模拟 ECAgent 与 Web 前端交互得到 twfID 的设想, 但由于和官方客户端端口冲突不共存+不如直接分析 Web 协议简单没有实现.

手动截获 twfID 可以作为一种更简单的实现方法, 我明天添加一下.

**Comment by lyc8503** [comment]
已经在 https://github.com/lyc8503/EasierConnect/releases/tag/TestBuild9 中实现.

**Comment by Hagb** [comment]
将前面所说的大致实现了一下，在 7.6.3 上测试了可用
https://github.com/Hagb/easyconnect-weblogin-capture

btw，用户遇到不支持的登录方式时，或许可以用上面的方式使用官方客户端登录一次，捕获的日志经过脱敏后应该可以发出来。（虽然技术上来说这种日志不是首选格式，但是我所能想到其他抓包记录格式似乎都不太方便脱敏）

update: 7.6.7 官方客户端似乎会在登录过程中跳转，或许需要配合 dnat 使用？（或者在 http 的层面上把跳转目的地给改了）

> 在 GNU/Linux 版的 EasyConnect 官方客户端中，对这个深信服的服务进程或许可以做到（相比于 docker/podman）较为轻量级的隔离（待验证）。

关于这个还没有找到特别好的方式，现在没有 root 的情况下 EasyConnect 客户端获取“硬件 ID”会遇到某些问题。单纯通过用户名、密码登录的已经可以做到了（不过好像也没什么用）。

**Comment by lyc8503** [comment]
确实, 抓取流量的问题主要是数据脱敏比较麻烦, 我觉得需要在记录登录的过程中自动替换掉域名+账号+密码(即使加盐且被 RSA 加密了)以及 TwfID, 跳转的话应该用 mitmproxy 替换一下地址应该可以解决?

Linux 客户端没研究过, 主要是对 Windows 客户端进行的分析, 各个进程间联系挺紧密的, 分开只用一部分还是比较麻烦.

我觉得用 Docker 封印 EasyConnect 这个做法本身没问题, 适用大部分场景了, 我想如果直接将 Docker 中 ECAgent 的端口映射到主机让用户直接可以在主机浏览器中登录 EasyConnect 而不要使用 vnc 是不是会更方便一些.

**Comment by Hagb** [comment]
> 确实, 抓取流量的问题主要是数据脱敏比较麻烦, 我觉得需要在记录登录的过程中自动替换掉域名+账号+密码(即使加盐且被 RSA 加密了)以及 TwfID, 跳转的话应该用 mitmproxy 替换一下地址应该可以解决?

替换域名刚刚试了一下应该可以，不过要精确地替换似乎有点复杂。此外还发现有时候会 `GET /com/server.crt` 获取服务端的证书，然后客户端用这个证书来和服务器通讯，这个也得替换掉。

> Linux 客户端没研究过, 主要是对 Windows 客户端进行的分析, 各个进程间联系挺紧密的, 分开只用一部分还是比较麻烦.

Linux 客户端的前端（Electron 实现的 GUI）和后端（负责登录、建立隧道的部分）相对比较分离，两者也是通过 54530 端口通讯。后端也是分成几个文件。似乎可以去除掉一些部分（比如前端）来减小体积。（现在还有一个想法是把 web api 的部分搬到 Android 上去，然后结合 EasierConnect 使用）

印象中 Linux 端和 Windows 客户端有些地方类似？Linux 端上 `ECAgent` 提供 54530 端口的 api，`CSClient` 似乎是负责某些认证相关的操作，`svpnservice` 创建和管理虚拟网卡。

> 我觉得用 Docker 封印 EasyConnect 这个做法本身没问题, 适用大部分场景了

嗯，不过我个人的出发点是尽可能使用 foss：让用户优先尝试开源客户端，之后如果开源实现不支持某种登录方式的话，也可以尽量使用开源客户端（比如只保留闭源客户端里面 web 登录需要的一小部分，剩下的交给开源客户端），同时提供一些较为容易使用的方式来给开源客户端实现这部分功能提供相关的信息（比如容易获得的日志），开源客户端的功能支持得越多 闭源客户端就可以用得越少。（大概我这么说也有点站着说话不腰疼，毕竟维护项目也需要时间和精力。如果感兴趣的人多的话似乎还可以仿照 https://github.com/drcoms 或者 https://github.com/project-mirai/ 这种形式？）

> 我想如果直接将 Docker 中 ECAgent 的端口映射到主机让用户直接可以在主机浏览器中登录 EasyConnect 而不要使用 vnc 是不是会更方便一些.

嗯嗯，是的。现在也加了这个支持。
