### ISSUE TITLE
希望能提供相关教程

### ISSUE THREAD

**Issue by dev-lake** [lyc8503/EasierConnect#41]
我对这一块怎么实现的非常感兴趣，尤其是逆向的的思路，希望作者能出个教程，个人愿意付费

**Comment by lyc8503** [comment]
其实这个 VPN 的私有协议不是很复杂，我实际分析过程中也没用到啥 IDA Pro 之类的逆向工具，主要还是抓包分析

教程算不上，分享思路的博客之前就写过了：https://blog.lyc8503.site/post/nju-ssl-vpn-protocol/

不过这个 VPN 有许多不同版本，官方后来可能也有升级更新，文章不一定能复现了，思路仅供参考学习

对你有帮助的话欢迎文末二维码donate~

**Comment by dev-lake** [comment]
好的，感谢回复
